package com.fleetmind.corecalc;

public enum QualityFlag {
    MISSING_WIND_SCALE,
    HIGH_WIND,
    INVALID_FULL_SPEED_HOURS,
    INSUFFICIENT_FULL_SPEED_HOURS,
    PARSE_ERROR,
    MISSING_FUEL_CONSUMP,
    INVALID_FUEL_CONSUMP,
    NONFINITE_FOC,
    NON_INTEGER_WIND_SCALE
}
